# OpenHousing Configuration
# Конфигурация плагина OpenHousing

# Основные настройки
general:
  # Префикс плагина в сообщениях
  prefix: "&6[OpenHousing]&r"
  
  # Язык плагина (ru, en)
  language: "ru"
  
  # Отладочный режим
  debug: false
  
  # Автосохранение данных (в минутах)
  auto-save-interval: 10

# Настройки базы данных
database:
  # Тип базы данных (h2, mysql)
  type: "h2"
  
  # Настройки H2 (локальная база)
  h2:
    file: "openhousing.db"
  
  # Настройки MySQL
  mysql:
    host: "localhost"
    port: 3306
    database: "openhousing"
    username: "root"
    password: ""
    ssl: false
    
  # Настройки пула соединений
  pool:
    maximum-pool-size: 10
    minimum-idle: 2
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000

# Настройки Housing системы (каждый дом - отдельный мир)
housing:
  # Максимальное количество домов на игрока
  max-houses-per-player: 3
  
  # Стоимость создания дома
  creation-cost: 50000.0
  
  # Префикс для названия миров домов
  world-prefix: "house_"
  
  # Тип мира по умолчанию
  default-world-type: "FLAT"
  
  # Сложность мира дома
  world-difficulty: "PEACEFUL"
  
  # Настройки мира
  world-settings:
    # Отключить спавн мобов
    mob-spawning: false
    # Отключить генерацию структур
    generate-structures: false
    # Держать спавн в памяти
    keep-spawn-in-memory: true

# Настройки системы кода с поддержкой строк
coding:
  # Максимальное количество блоков в скрипте
  max-blocks-per-script: 500
  
  # Максимальное количество строк в скрипте
  max-lines-per-script: 50
  
  # Максимальное количество блоков в строке
  max-blocks-per-line: 20
  
  # Максимальное время выполнения скрипта (в миллисекундах)
  max-execution-time: 5000
  
  # Максимальная глубина вложенности блоков
  max-nesting-depth: 20
  
  # Разрешенные события для обработки
  allowed-events:
    - "player_join"
    - "player_quit"
    - "player_chat"
    - "player_move"
    - "player_interact"
    - "player_damage"
    - "block_break"
    - "block_place"
  
  # Автосохранение скриптов
  auto-save-scripts: true
  
  # Интервал автосохранения (в секундах)
  auto-save-interval: 30
  
  # Настройки строк
  line-settings:
    # Автоматически создавать первую строку
    auto-create-first-line: true
    # Имя первой строки по умолчанию
    default-first-line-name: "Главная строка"

# Настройки режимов дома
house-modes:
  # Режим строительства
  build-mode:
    # Разрешить ломать блоки
    allow-break: true
    # Разрешить ставить блоки
    allow-place: true
    # Разрешить использовать команды
    allow-commands: true
    # Полет в режиме строительства
    allow-flight: true
  
  # Режим игры
  play-mode:
    # Запретить ломать блоки
    allow-break: false
    # Запретить ставить блоки
    allow-place: false
    # Ограниченные команды
    allow-commands: false
    # Запретить полет
    allow-flight: false

# Настройки экономики
economy:
  # Использовать Vault для экономики
  use-vault: true
  
  # Начальная сумма для новых игроков
  starting-balance: 1000.0
  
  # Ежедневная награда
  daily-reward:
    enabled: true
    amount: 500.0

# Настройки производительности
performance:
  # Максимальное количество одновременно выполняющихся скриптов
  max-concurrent-scripts: 50
  
  # Асинхронное выполнение тяжелых операций
  async-heavy-operations: true
  
  # Кэширование данных
  cache:
    enabled: true
    # Время жизни кэша (в минутах)
    ttl: 30
    # Максимальный размер кэша
    max-size: 1000

# Интеграции с другими плагинами
integrations:
  # PlaceholderAPI
  placeholderapi:
    enabled: true
  
  # WorldEdit
  worldedit:
    enabled: true
    # Использовать WorldEdit для операций с миром
    use-for-world-operations: true
  
  # ReActions
  reactions:
    enabled: true
